default_config:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  temperature_unit: F
  time_zone: America/Chicago
#  packages: !include_dir_named packages

http:
  base_url: base_url
  ip_ban_enabled: true
  login_attempts_threshold: 5

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Vera
vera:
  vera_controller_url: !secret vera_controller_url
  
ifttt:
    key: !secret ifttt_key

sensor:
  - platform: flunearyou

pi_hole:
  host: !secret pihole_host
  ssl: false
  verify_ssl: false
